# Generated by Django 4.2.6 on 2023-11-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchangerates.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10, validators=[exchangerates.validators.validate_positive_nonzero])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency_exchange_rates', to='exchangerates.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currencies_exchange_rates', to='exchangerates.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10, validators=[exchangerates.validators.validate_positive_nonzero])),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('permanent', 'permanent'), ('temporary', 'temporary')], default='permanent', max_length=10)),
                ('result', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='exchangerates.exchangerate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
