# Generated by Django 4.2.6 on 2023-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='status',
            field=models.CharField(choices=[('permanent', 'permanent'), ('temporary', 'temporary')], default='temporary', max_length=10),
        ),
    ]
