# Generated by Django 4.2.6 on 2023-11-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0003_alter_currencyconversion_conversion_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency'], name='exchangerat_from_cu_201b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['to_currency'], name='exchangerat_to_curr_688119_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency'], name='exchangerat_from_cu_1db715_idx'),
        ),
    ]
