# Generated by Django 4.2.6 on 2023-11-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0004_exchangerate_exchangerat_from_cu_201b2b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyconversion',
            options={'ordering': ['-conversion_date']},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-timestamp']},
        ),
    ]
